version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis-server
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - redis_data:/bitnami/redis/data
    restart: always

volumes:
  redis_data:
    driver: local
