[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hemmorphi = "9m9Jxk8tMmjphGgCRBCS5wnr9VXFSqmjGkDxVcpcfj2J"

[programs.devnet]
hemmorphi = "9m9Jxk8tMmjphGgCRBCS5wnr9VXFSqmjGkDxVcpcfj2J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
