import { Header } from '@/components/layout/Header';
import ToastProvider from '@/components/Toastify/ToastProvider';
import { TokenProvider } from '@/components/TokenProvider/TokenProvider';
import type { Metadata } from 'next';
import SolanaProvider from '../components/Solana/SolanaProvider';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <TokenProvider>
          <SolanaProvider>
            <ToastProvider>
              <Header />
              {children}
            </ToastProvider>
          </SolanaProvider>
        </TokenProvider>
      </body>
    </html>
  );
}
